on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Set up go
        uses: actions/setup-go@4
        with:
          go-version: '1.22'

      - name: Build
        run: scripts/buildprod.sh
